function toItemOrdemServicoV2Dto(item) {
  return {
    id: item.id,
    ordem_servico_id: item.ordem_servico_id,
    item_pai_id: item.item_pai_id,
    retorno_garantia_de_item_id: item.retorno_garantia_de_item_id,
    descricao: item.descricao,
    categoria: item.categoria,
    tipo: item.tipo,
    origem: item.origem,
    execucao_direta: Boolean(item.execucao_direta),
    exige_diagnostico: Boolean(item.exige_diagnostico),
    autorizacao_status: item.autorizacao_status,
    pagamento_status: item.pagamento_status,
    status_item: item.status_item,
    prioridade: item.prioridade,
    quantidade: item.quantidade,
    valor_unitario: item.valor_unitario,
    valor_total: item.valor_total,
    data_prometida: item.data_prometida,
    previsao_peca_atual: item.previsao_peca_atual,
    observacoes: item.observacoes,
    criado_por: item.criado_por,
    criado_por_nome: item.criado_por_nome,
    garantia_aplicavel: Boolean(item.garantia_aplicavel),
    criado_em: item.criado_em,
    iniciado_em: item.iniciado_em,
    concluido_em: item.concluido_em,
    cancelado_em: item.cancelado_em,
    atualizado_em: item.atualizado_em,
  };
}

function toOrdemServicoV2Dto(ordemServico, items = []) {
  return {
    id: ordemServico.id,
    numero_os: ordemServico.numero_os,
    cliente_id: ordemServico.cliente_id,
    cliente_nome: ordemServico.cliente_nome,
    cliente_telefone: ordemServico.cliente_telefone,
    motocicleta_id: ordemServico.motocicleta_id,
    motocicleta_marca: ordemServico.motocicleta_marca,
    motocicleta_modelo: ordemServico.motocicleta_modelo,
    motocicleta_ano: ordemServico.motocicleta_ano,
    motocicleta_cor: ordemServico.motocicleta_cor,
    motocicleta_placa: ordemServico.motocicleta_placa,
    numero_externo: ordemServico.numero_externo || null,
    valor_total_ordem: Number(ordemServico.valor_total_ordem || 0),
    valor_pendente_ordem: Number(ordemServico.valor_pendente_ordem || 0),
    usuario_abertura_id: ordemServico.usuario_abertura_id,
    usuario_abertura_nome: ordemServico.usuario_abertura_nome,
    queixa_principal: ordemServico.queixa_principal,
    observacoes_entrada: ordemServico.observacoes_entrada,
    observacoes_internas: ordemServico.observacoes_internas,
    data_prometida: ordemServico.data_prometida,
    prioridade_agregada: ordemServico.prioridade_agregada,
    status_geral: ordemServico.status_geral,
    km_entrada: ordemServico.km_entrada,
    buscar_moto: Boolean(ordemServico.buscar_moto),
    endereco_retirada: ordemServico.endereco_retirada,
    fotos_entrada_count: Number(ordemServico.fotos_entrada_count || 0),
    cadastro_fotos_finalizado: Boolean(ordemServico.cadastro_fotos_finalizado),
    legado_atendimento_id: ordemServico.legado_atendimento_id,
    aberta_em: ordemServico.aberta_em,
    pronta_retirada_em: ordemServico.pronta_retirada_em,
    retirada_em: ordemServico.retirada_em,
    finalizada_em: ordemServico.finalizada_em,
    arquivada_em: ordemServico.arquivada_em,
    cancelada_em: ordemServico.cancelada_em,
    criado_em: ordemServico.criado_em,
    atualizado_em: ordemServico.atualizado_em,
    items: items.map(toItemOrdemServicoV2Dto),
  };
}

module.exports = {
  toItemOrdemServicoV2Dto,
  toOrdemServicoV2Dto,
};
