ALTER USER 'root'@'localhost' IDENTIFIED BY 'RootDev123!';
CREATE USER IF NOT EXISTS 'jebil_dev'@'localhost' IDENTIFIED BY 'JebilDev123!';
CREATE USER IF NOT EXISTS 'jebil_dev'@'127.0.0.1' IDENTIFIED BY 'JebilDev123!';
GRANT ALL PRIVILEGES ON *.* TO 'jebil_dev'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'jebil_dev'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;
